controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz
  arm_controller:
    type: joint_trajectory_controller/JointTrajectoryController
  
  joint_state_broadcaster:
    type: joint_state_broadcaster/JointStateBroadcaster


arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - joint2_to_joint1
      - joint3_to_joint2
      - joint4_to_joint3
      - joint5_to_joint4
      - joint6_to_joint5
      - joint6output_to_joint6